welcome = input("\nWelcome, please enter your name\n")
print("\nYour name is " + welcome + ".")
ask = int(input("\nPlease enter a number\n"))
num2 = int(input("\nPlease enter anothet number\n"))
print("The sum is ", ask + num2,".")
