print("Welcome to the FREE version of Calculator++! This calculator has the ability to divide. This calculator is only compatible with two numbers. If you have any issue with this calculator then go to this link:\n https://github.com/aramservices198/Unimaginable-Python-Projects/issues/new")
num1 = float(input("First Number?"))
num2 = float(input("Second Number?"))
result = (num1 / num2 )
print(result)
