print("Do you want to do a surprise!? If you don't, than STOP this program.")
print("Lunch Room!")
name = input("Pick your name, or a nickname.")
adjective = input("Pick an adjective.")
adjective1 = input("Pick another adjective.")
adjective2 = input("Pick a third adjective.")
animal = input("Pick a cow, sheep, goat, beef or any meat.")
vegetable = input("Pick a vegetable.")
vegetable1 = input("Pick another vegetable.")
color = input("Pick a Color.")
container = input("Pick a container name for lunch.")
noun = input("Pick a noun.")
print("These are your choices. " + "Your name is " + name + ". Your container's name is " + container + ". Your adjectives are " + adjective + ", " + adjective1 + ", and " + adjective2 + ". Your vegetables are " + vegetable + " and " + vegetable1 + ". Your noun is " + noun + ". And last but not least, your animal-meat is " + animal + ".")
print("Make sure your lunch " + container + " is\n" + "filled with nutritious " + adjective + " food. Do \nnot go to the " + adjective1 + " food stand across \nthe street from school. The hamburgers they \nserve are fried in " + noun + " and are made \nof " + animal + " meat. So take a sandwich made \nof " + vegetable + " or, " + vegetable1 + " it's much \nhealthier! Drink " + color + " milk instead of \n" + adjective2 + " colas." + " Thanks, " + name + " for solving my MADLIBS problem!")
