adjective = input("Pick an adjective:")
adjective1 = input("Pick another adjective:")
adjective2 = input("Pick another adjective:")
noun = input("Pick a noun:")
noun1 = input("Pick another noun:")
noun2 = input("Pick another noun:")
plural_noun = input("Pick a plural noun:")
plural_noun1 = input("Pick another plural noun:")
plural_noun2 = input("Pick another plural noun:")
plural_noun3 = input("Pick another plural noun:")
game = input("Pick a game:")
dialect = ("ing")
verb_ending_in_ing = input("Pick a verb ending in -ing:")
verb_ending_in_ing1 = input("Pick another verb ending in -ing:")
verb_ending_in_ing2 = input("Pick another verb ending in -ing:")
verb_ending_in_ing3 = input("Pick another verb ending in -ing:")
plant = input("Pick a plant:")
place = input("Pick a place:")
number = input("Pick a number:")
print("Your adjectives are:\n" + adjective + "\n" + adjective1 + "\n" + adjective2)
print("Your nouns are:\n" + noun + "\n" + noun1 + "\n" + noun2)
print("Your plural nouns are:\n" + plural_noun + "\n" + plural_noun1 + "\n" + plural_noun2 + "\n" + plural_noun3)
print("Your game is:\n" + game)
print("Your verbs ending in " + dialect + " are:" + "\n" + verb_ending_in_ing + "\n" + verb_ending_in_ing1 + "\n" + verb_ending_in_ing2 + "\n" + verb_ending_in_ing3)


