print("This is an Addition Calculator, you will need to go to the website for other calculations. ")
num1 = input("Enter a number : ")
num2 = input("Enter a another number : ")
result = float(num1) + float(num2)
print(result)